import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {getStoryProgress,saveStoryProgress,resetStoryProgress} from '../src/lib/story/progress';
import {continueUrl,hasAdventure,trackedQuests,journalQuests,SIDEQUESTS,acceptSidequest,advanceSidequest,getStorySettings,saveStorySettings} from '../src/lib/story/adventure';
describe('adventure saves and journal',()=>{
 beforeEach(()=>{const data=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)});vi.stubGlobal('window',{dispatchEvent:vi.fn()});});
 afterEach(()=>{SIDEQUESTS.length=0;vi.unstubAllGlobals();});
 it('starts without a Continue save, then saves a new adventure',()=>{expect(hasAdventure(getStoryProgress())).toBe(false);expect(saveStoryProgress({startedAt:1})).toBe(true);expect(hasAdventure(getStoryProgress())).toBe(true);expect(continueUrl(getStoryProgress())).toBe('/story/1');});
 it('keeps legacy saves compatible and respects locked routes',()=>{saveStoryProgress({completedChapters:[1]});expect(continueUrl(getStoryProgress())).toBe('/story/village');saveStoryProgress({resumeArea:'wordwood',opening:'scholar'});expect(continueUrl(getStoryProgress())).toBe('/story/1');saveStoryProgress({opening:'wordwood'});expect(continueUrl(getStoryProgress())).toBe('/story/2');});
 it('manual saves do not erase puzzles or expedition state',()=>{saveStoryProgress({wordwoodExpedition:{tablet:true},chapterCheckpoints:{2:'{"solved":true}'}});saveStoryProgress({resumeArea:'wordwood'});expect(getStoryProgress().wordwoodExpedition?.tablet).toBe(true);expect(getStoryProgress().chapterCheckpoints[2]).toContain('solved');expect(getStoryProgress().savedAt).toBeGreaterThan(0);});
 it('tracks discovered optional objectives alongside the main quest and preserves completed records',()=>{saveStoryProgress({opening:'wordwood',completedChapters:[1],wordwoodExpedition:{tablet:true,logGuardianFreed:true},trackedQuest:'a-place-to-rest'});acceptSidequest('a-place-to-rest');expect(trackedQuests(getStoryProgress()).map(q=>q.id)).toContain('a-place-to-rest');expect(journalQuests(getStoryProgress()).find(q=>q.id==='lost-keepers')?.status).toBe('completed');expect(journalQuests(getStoryProgress()).some(q=>q.id==='field-notes')).toBe(false);});
 it('supports accepting and completing future authored sidequests',()=>{SIDEQUESTS.push({id:'test',title:'Test',location:'Village',description:'A task',steps:[{id:'one',text:'One'}]});expect(advanceSidequest('test','one')).toBe(false);expect(acceptSidequest('test')).toBe(true);expect(acceptSidequest('test')).toBe(false);expect(advanceSidequest('test','bad')).toBe(false);expect(advanceSidequest('test','one')).toBe(true);expect(journalQuests(getStoryProgress()).find(q=>q.id==='test')?.status).toBe('completed');});
 it('reset preserves settings and unrelated profile data',()=>{localStorage.setItem('profile','cosmetics');saveStorySettings({sound:false,volume:.2,reducedMotion:true});saveStoryProgress({startedAt:1});resetStoryProgress();expect(hasAdventure(getStoryProgress())).toBe(false);expect(getStorySettings().sound).toBe(false);expect(localStorage.getItem('profile')).toBe('cosmetics');});
 it('reports storage failure without pretending to save',()=>{vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{throw Error('full');}});expect(saveStoryProgress({startedAt:1})).toBe(false);});
});
