import type {StoryProgress} from '@/lib/story/progress';
import {getStoryInventory} from '@/lib/story/progress';
import {ARTS,RINGS,INKBURSTS,combatLoadout,saveCombatLoadout,type ArtId,type HeartRingId,type InkburstId} from '@/lib/story/combatLoadout';
import s from './AdventureUI.module.css';
import CombatGlyph from './CombatGlyph';
export default function CombatLoadoutScreen({progress,onError}:{progress:StoryProgress;onError:()=>void}){
 if(progress.combatArtsUnlocked!==true)return <><div className={s.pageHeading}><span>III</span><h2>Combat Arts</h2></div><section className={s.loadoutCard} aria-label="Combat Arts locked"><h3>Locked</h3><p>There is more to learn about the ways of ink.</p><p>Combat Arts will unlock later in your journey.</p></section></>;
 const loadout=combatLoadout(progress),owned=getStoryInventory().unlockedWeapons;
 const save=(next:typeof loadout)=>{if(!saveCombatLoadout(next))onError();};
 function art(slot:0|1,id:ArtId){const arts=[...loadout.arts] as [ArtId,ArtId],other=slot===0?1:0;if(arts[other]===id)arts[other]=arts[slot];arts[slot]=id;save({...loadout,arts});}
 return <><div className={s.pageHeading}><span>III</span><h2>Combat Loadout</h2></div><p className={s.paperNote}>Two Arts · one Heart Ring · one Inkburst. Choose a fighting style, not a stronger sword.</p>
 <div className={s.loadoutArts}>{([0,1] as const).map((slot)=>{const selected=ARTS.find(a=>a.id===loadout.arts[slot])!;return <section className={s.loadoutCard} key={slot}><div className={s.badgeHeading}><CombatGlyph id={selected.id}/><label><kbd>{slot===0?'Z':'X'}</kbd> Art {slot+1}<select aria-label={`Art ${slot+1}`} value={selected.id} onChange={e=>art(slot,e.target.value as ArtId)}>{ARTS.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div><div className={s.badgeChoices}>{ARTS.map(a=><button key={a.id} title={a.name} aria-label={`Equip ${a.name} in Art ${slot+1}`} aria-pressed={selected.id===a.id} onClick={()=>art(slot,a.id)}><CombatGlyph id={a.id} size={38}/></button>)}</div><p>{selected.description}</p><small>{selected.cooldown/1000}s cooldown · {selected.tool??'No tool required'}</small></section>;})}</div>
 <section className={s.loadoutCard}><div className={s.badgeHeading}><CombatGlyph id={loadout.ring}/><label>Heart Ring<select aria-label="Heart Ring" value={loadout.ring} onChange={e=>save({...loadout,ring:e.target.value as HeartRingId})}>{RINGS.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className={s.badgeChoices}>{RINGS.map(r=><button key={r.id} title={r.name} aria-label={`Equip ${r.name}`} aria-pressed={r.id===loadout.ring} onClick={()=>save({...loadout,ring:r.id})}><CombatGlyph id={r.id} size={38}/></button>)}</div></div><p>{RINGS.find(r=>r.id===loadout.ring)?.description}</p></section>
 <section className={s.loadoutCard}><div className={s.badgeHeading}><CombatGlyph id={loadout.inkburst}/><label><kbd>C</kbd> Inkburst<select aria-label="Inkburst" value={loadout.inkburst} onChange={e=>save({...loadout,inkburst:e.target.value as InkburstId})}>{INKBURSTS.map(b=><option key={b.id} value={b.id} disabled={!owned.includes(b.tool)}>{b.name}{owned.includes(b.tool)?'':` · ${b.tool==='bow'?'Help Luma':'Lexica shop'}`}</option>)}</select></label><div className={s.badgeChoices}>{INKBURSTS.map(b=><button key={b.id} title={owned.includes(b.tool)?b.name:`${b.name} · ${b.tool==='bow'?'Help Luma':'Lexica shop'}`} aria-label={`Equip ${b.name}`} disabled={!owned.includes(b.tool)} aria-pressed={b.id===loadout.inkburst} onClick={()=>save({...loadout,inkburst:b.id})}><CombatGlyph id={b.id} size={38}/></button>)}</div></div><p>{INKBURSTS.find(b=>b.id===loadout.inkburst)?.description}</p><small>Consumes 100 Ink. Earn Ink from hits, perfect guards, and first-time Word Seals.</small></section>
 <p className={s.paperNote}>Tools: Q / R / F · Arts: Z / X · Inkburst: C. Touch buttons use the same actions. Swap two matching Arts to keep each slot distinct.</p></>;
}
