import type { VillageBuildingId } from './buildings';

export const INTERIOR_PALETTES = ['teal', 'rust', 'moss', 'plum'] as const;
export type InteriorPalette = typeof INTERIOR_PALETTES[number];
export const INTERIOR_ASSETS = ['way-sign','stone-seed','stone-sprout','stone-bloom','shelf','cupboard','chest','table','tea-table','desk','map','washstand','hearth','bread','barrel','plant','seed-shelf','armour','lectern','candles','chimes','mural','tablet','floor','stone','wall','beam','skirting','window','threshold',
  'tavern-table-nw','tavern-table-ne','tavern-table-sw','tavern-table-se','tea-shelf','tea-service','tea-feast','double-bed-head-left','double-bed-head-right','double-bed-foot-left','double-bed-foot-right',
  'beam-base','outpost-pillar-cap','outpost-pillar-shaft','outpost-pillar-base','archery-target','workbench','bridge-clamp','tool-rack','rain-frame','rain-collector','gallery-lectern','seed-bin','drying-herbs',
  'rope-coil','sawhorse','sluice-wheel','specimen-case','gallery-bench','potting-tray','root-basket',
  'bridge-model-left','bridge-model-right','rain-cascade-top','rain-cascade-basin','garden-spades','seed-sacks','seedling-rack','rain-relief',
  'spring-canopy-left','spring-canopy-middle','spring-canopy-right','spring-basin-left','spring-basin-middle','spring-basin-right',
  'counter-straight','counter-ledger','counter-corner','counter-side','counter-end',
  'inn-door-top','inn-door-bottom','inn-stairs-top','inn-stairs-middle','inn-stairs-foot',
  ...INTERIOR_PALETTES.flatMap(p=>['bed-head','bed-foot','chair',...['tl','tc','tr','ml','mc','mr','bl','bc','br'].map(part=>`rug-${part}`)].map(k=>`${k}-${p}`))];
export type InteriorId = VillageBuildingId | 'archive';
export interface RoomProp { asset:string; col:number; row:number; label:string; line:string; }
export interface InteriorPlan { palette:InteriorPalette; stone?:boolean; rug:[number,number,number,number]; props:RoomProp[]; }
const prop=(asset:string,col:number,row:number,label:string,line:string):RoomProp=>({asset,col,row,label,line});
const bed=(col:number,row:number,owner:string):RoomProp[]=>[
  prop('bed-head',col,row,`${owner==='YOUR'?'YOUR':owner+'’S'} BED`,'A linen pillow, a hand-stitched quilt, and a sturdy oak bedframe.'),
  prop('bed-foot',col,row+1,`${owner==='YOUR'?'YOUR':owner+'’S'} QUILT`,'Someone has mended the same corner three times. It must be a favourite.'),
];
const chair=(col:number,row:number)=>prop('chair',col,row,'CHAIR','The seat is worn smooth. This is somebody’s favourite spot.');
const plant=(col:number,row:number)=>prop('plant',col,row,'POTTED HERBS','Fresh leaves turn toward the window. The clay pot is still damp.');
const shelf=(col:number,row:number)=>prop('shelf',col,row,'BOOKSHELF','Bound journals and stitched paperbacks. The most-loved spines have been repaired.');
export const INTERIOR_PLANS:Record<InteriorId,InteriorPlan>={
  home:{palette:'teal',rug:[4,3,3,3],props:[...bed(0,0,'YOUR'),prop('chest',2,0,'YOUR CHEST','Bellum’s letter is here. It is dated tomorrow.'),shelf(3,0),prop('hearth',5,0,'HEARTH','A kettle rests beside the embers. Home still smells of cedar.'),prop('washstand',8,0,'WASHSTAND','A pitcher, a wooden basin, and a clean folded towel.'),prop('cupboard',9,0,'CUPBOARD','Two bowls. Three mugs. Somehow you always use the chipped one.'),prop('tea-table',5,4,'BREAKFAST','A note under your cup: Eat before you leave. — Mira'),chair(4,4),chair(6,4),plant(10,6)]},
  baker:{palette:'rust',rug:[6,3,3,2],props:[prop('hearth',0,0,'BREAD OVEN','A warm brick oven. A floury handprint marks the mantel.'),prop('bread',1,0,'COOLING LOAVES','Fenn has counted the loaves. He has also counted Pip.'),prop('barrel',3,0,'FLOUR BARREL','A scoop hangs inside. Someone has drawn a smiling face in the flour.'),prop('cupboard',4,0,'BAKING CUPBOARD','Cinnamon, honey, and the emergency biscuit tin.'),...bed(9,0,'FENN'),prop('bread',2,3,'BAKING TABLE','The recipe says “one pinch.” Below: YOUR pinch, Fenn. Not Serif’s.'),prop('desk',3,3,'RECIPE BOOK','Butter stains have made the best recipes easy to find.'),chair(2,4),prop('tea-table',7,4,'SUPPER','Yesterday’s rolls. Still good for dipping.'),plant(0,6)]},
  gardener:{palette:'moss',rug:[3,3,3,3],props:[...bed(0,0,'BRAMBLE'),...bed(10,0,'TANSY'),plant(2,0),prop('seed-shelf',4,0,'SEED JARS','Every jar has a date and a tiny drawing.'),prop('washstand',6,0,'POTTING BASIN','A small frog is borrowing the basin. Best leave it be.'),plant(8,0),plant(8,2),prop('seed-shelf',9,3,'CUTTINGS','Mint. Also mint. A third label says STOP PLANTING MINT.'),prop('desk',4,4,'GARDEN JOURNAL','First bloom: yesterday. Bramble has underlined it twice.'),chair(3,4),prop('barrel',0,5,'RAIN BARREL','A wooden dipper floats on the rainwater.'),plant(10,6)]},
  guard:{palette:'teal',rug:[4,2,3,4],props:[prop('armour',0,0,'ARMOUR STAND','Polished armour. A dent shaped suspiciously like a rolling pin.'),prop('chest',1,0,'EQUIPMENT CHEST','Spare socks. More spare socks. One extremely serious helmet.'),prop('hearth',4,0,'HEARTH','The night watch’s porridge is still keeping warm.'),...bed(9,0,'SERIF'),prop('cupboard',8,0,'UNIFORM CUPBOARD','Every tunic faces the same way. One is clearly inside out.'),prop('map',5,3,'PATROL MAP','Serif has given himself every night shift.'),chair(5,4),prop('armour',0,4,'PRACTICE SWORDS','Blunted edges. The grips have been carefully rewrapped.'),plant(10,6)]},
  guest:{palette:'plum',rug:[3,3,4,3],props:[...bed(0,0,'OREN'),...bed(3,0,'ROWAN'),prop('chest',2,0,'UNPACKED BOXES','Kitchen things. Winter things. A box labelled: Find out what these are.'),shelf(5,0),prop('hearth',6,0,'HEARTH','A pot of stew. Oren has written the recipe on the mantel.'),prop('washstand',8,0,'WASHSTAND','One towel, carefully folded. One brush, not so carefully cleaned.'),prop('cupboard',9,0,'CUPBOARD','A purple thumbprint marks the handle.'),prop('desk',1,4,'HOUSEHOLD NOTES','Fix shelf. Buy onions. Stop using boxes to fix shelf.'),chair(1,5),prop('tea-table',6,4,'SUPPER TABLE','Bread, cheese, and a place set for a friend.'),plant(10,6)]},
  nell:{palette:'rust',rug:[4,3,3,3],props:[...bed(0,0,'NELL'),prop('cupboard',2,0,'SEWING CUPBOARD','Buttons sorted by colour. One jar is labelled: Nearly matching.'),shelf(4,0),prop('hearth',6,0,'HEARTH','A basket of crooked rolls warms beside the fire.'),prop('washstand',9,0,'WASHSTAND','A blue towel embroidered with Nell’s initials.'),prop('desk',2,3,'MENDING TABLE','A scarf, three wooden buttons, and a note: Fenn, stop washing this so hot.'),chair(2,4),prop('tea-table',5,4,'AFTERNOON TEA','Two cups and a plate of the bakery’s less symmetrical efforts.'),prop('chest',0,6,'WOOL CHEST','Soft wool, neatly wound. The green ball has escaped.'),plant(10,6)]},
  mapmaker:{palette:'rust',rug:[3,3,4,3],props:[...bed(0,0,'MIRA'),...bed(2,0,'LUMA'),prop('chest',3,0,'LUMA’S TOY CHEST','A wooden dragon guards a collection of interesting stones.'),shelf(5,0),prop('washstand',8,0,'WASHSTAND','Two towels: one neat, one hanging by a single corner.'),prop('hearth',10,0,'HEARTH','A small pair of boots dries beside the fire.'),prop('map',4,4,'MIRA’S MAP','Bridges, paths, careful measurements. Ask Luma about the silver sleeve.'),prop('desk',5,4,'LUMA’S MAP','The bakery is enormous. Everything else fits around it.'),chair(3,4),chair(6,4),plant(10,6)]},
  scriptorium:{palette:'plum',rug:[4,2,3,4],props:[...bed(6,0,'PIP'),shelf(0,0),shelf(1,0),prop('seed-shelf',3,0,'INK JARS','Blue for rivers. Green for woods. Red for “check this again.”'),prop('lectern',5,0,'MASTER COPY','A carefully copied page. The margins are full of arguments.'),shelf(8,0),shelf(9,0),prop('desk',2,3,'COPYING DESK','A repaired sign: Bridge. Under it: Actually a bridge this time.'),chair(2,4),prop('desk',7,3,'LETTER DESK','An unfinished letter begins “I should have told you sooner.”'),chair(7,4),prop('chest',0,6,'TOOLS','Three rulers. One is labelled DO NOT TRUST.'),prop('candles',10,6,'CANDLES','Each candle has been trimmed to the same height. Almost.') ]},
  'tea-room':{palette:'moss',rug:[5,2,5,4],props:[
    prop('tea-shelf',0,0,'TEA TINS','Apple peel, mossbell, toasted barley. The good leaves are saved for company.'),prop('tea-shelf',1,0,'HOUSE BLENDS','Nell has crossed out “secret recipe” and written “ask nicely.”'),prop('washstand',3,0,'CLEAN CUPS','No two mugs match. Every regular knows their own.'),
    prop('counter-straight',0,2,'OAK BAR','Boot scuffs polish the footrail.'),prop('tea-service',1,2,'HOUSE POT','A heavy copper teapot, ready for another round.'),prop('counter-straight',2,2,'HONEY & LEMON','Help yourself. Leave some for Pip.'),prop('counter-corner',3,2,'THE MOSSBELL BAR','A warm cup and a seat for anyone who needs one.'),
    prop('counter-side',3,3,'BAR RETURN','The crockery is tucked safely behind the oak rail.'),
    prop('hearth',10,0,'KETTLE HEARTH','Logs settle under the singing kettle.'),prop('barrel',10,1,'BARLEY TEA','A cool brew for warm afternoons.'),
    ...(['nw','ne','sw','se'] as const).map((part,i)=>prop(`tavern-table-${part}`,6+i%2,3+Math.floor(i/2),'SHARED TABLE','A moss-green runner, warm mugs, and a plate passed from hand to hand.')),
    chair(0,3),chair(2,3),chair(5,3),chair(8,3),chair(6,5),chair(7,5),chair(9,5),
    prop('candles',0,7,'LAST LIGHT','The candles stay lit until the last guest leaves.'),plant(10,6)
  ]},
  archive:{palette:'teal',stone:true,rug:[4,2,3,5],props:[shelf(0,0),shelf(1,0),shelf(9,0),shelf(10,0),prop('tablet',5,1,'FIRST DICTIONARY','The missing entry once defined meaning itself.'),prop('chimes',1,3,'BELLUM’S MEMORY CHIMES','The chimes hold fragments of Bellum’s voice.'),prop('mural',9,3,'FOUNDING MURAL','A crack divides the two figures.'),prop('lectern',0,5,'CATALOGUE','A hundred careful hands have added to this catalogue.'),prop('lectern',10,5,'RESTORATION NOTES','Do not repair a word until you understand what it meant.'),prop('candles',3,0,'VIGIL CANDLES','Someone keeps the vigil even when the Archive is empty.'),prop('candles',7,0,'VIGIL CANDLES','Fresh wax on an old brass dish.')]},
};

export const ROOM_GRID={x:224,y:160,cols:11,floorY:224,rows:8,exit:{x:400,y:464},spawn:{x:400,y:432},resident:{x:496,y:368}};
export const propAsset=(prop:RoomProp,palette:InteriorPalette)=>['bed-head','bed-foot','chair'].includes(prop.asset)?`${prop.asset}-${palette}`:prop.asset;
