'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {getStoryProgress,resetStoryProgress,saveStoryProgress,type StoryProgress} from '@/lib/story/progress';
import {AREA_NAMES,continueUrl,currentQuest,hasAdventure} from '@/lib/story/adventure';
import StorySettings from '@/components/story/StorySettings';
import s from '@/components/story/AdventureUI.module.css';
export default function StoryTitle(){
 const router=useRouter(),[progress,setProgress]=useState<StoryProgress|null>(null),[settings,setSettings]=useState(false),[confirm,setConfirm]=useState<'new'|'reset'|null>(null),[error,setError]=useState('');
 useEffect(()=>{setProgress(getStoryProgress());},[]);
 const exists=progress&&hasAdventure(progress);
 function start(){try{resetStoryProgress();if(!saveStoryProgress({startedAt:Date.now(),resumeArea:'road'}))throw Error();router.push('/story/1');}catch{setError('Your browser could not save the new adventure. Please enable local storage.');}}
 function reset(){try{resetStoryProgress();setProgress(getStoryProgress());setConfirm(null);}catch{setError('Progress could not be reset. Please try again.');}}
 return <main className={s.screen}><section className={s.panel} aria-label="Story title screen"><p className={s.eyebrow}>Lexicon League · Story mode</p><div className={s.crest} aria-hidden="true">✧</div><h1 className={s.title}>An unwritten<br/>adventure.</h1><p className={s.muted}>Beyond the gate, the world is waiting.</p><div className={s.columns}><div className={s.stack}><button className={`${s.button} ${s.primary}`} disabled={!progress||!exists} onClick={()=>progress&&router.push(continueUrl(progress))}>Continue game</button><button className={s.button} disabled={!progress} onClick={()=>exists?setConfirm('new'):start()}>New game</button><button className={s.button} aria-expanded={settings} onClick={()=>{setSettings(!settings);setConfirm(null);}}>Settings</button><Link className={s.muted} href="/">Back to Lexicon League</Link></div><div className={s.card}>{settings?<><h2 className={s.heading}>Settings</h2><StorySettings/><div className={s.footer}><button className={`${s.button} ${s.danger}`} disabled={!exists} onClick={()=>setConfirm('reset')}>Reset game progress</button><p className={s.muted}>Only this adventure is reset. Your profile, cosmetics and settings stay.</p></div></>:<><p className={s.eyebrow}>{exists?'Your adventure':'A fresh page'}</p><h2 className={s.heading}>{exists?AREA_NAMES[progress.resumeArea??(progress.completedChapters.includes(1)?'village':'road')]:'Every story begins somewhere.'}</h2><p className={s.muted}>{exists?currentQuest(progress)?.title??'Explore the world at your own pace.':'Start a new game to answer the warning bell and discover what lies beyond Inkwell.'}</p><p className={s.muted}>{progress?.savedAt?`Last saved ${new Date(progress.savedAt).toLocaleString()}`:'Progress saves automatically in this browser.'}</p>{exists&&<p className={s.muted}>Continue returns to a safe arrival point in your last area.</p>}</>}</div></div>{confirm&&<section className={`${s.notice} ${s.footer}`} role="alertdialog" aria-modal="false" aria-label="Confirm progress reset"><h2 className={s.heading}>{confirm==='new'?'Begin again?':'Erase this adventure?'}</h2><p>This replaces your current story save. It cannot be undone.</p><div className={s.row}><button autoFocus className={s.button} onClick={()=>setConfirm(null)}>Keep my adventure</button><button className={`${s.button} ${s.danger}`} onClick={confirm==='new'?start:reset}>{confirm==='new'?'Erase save and start':'Erase story progress'}</button></div></section>}{error&&<p role="alert">{error}</p>}<p className={`${s.status} ${s.footer}`}>One adventure save · Stored on this device · Press M while playing for your adventure menu</p></section></main>;
}
