-- Expanded schools database for teacher verification
-- Adds a broad catalog of US K-12 schools across multiple states

INSERT INTO public.schools (name, city, state, normalized_name, verified_domains)
VALUES
  -- California
  ('Mission Bay High School', 'San Diego', 'CA', 'mission bay high school', ARRAY['missionbay.sandiegounified.org', 'sandi.net']),
  ('La Jolla High School', 'La Jolla', 'CA', 'la jolla high school', ARRAY['lajollahigh.org', 'sandiegounified.org']),
  ('Point Loma High School', 'San Diego', 'CA', 'point loma high school', ARRAY['pointloma.sandiegounified.org']),
  ('Scripps Ranch High School', 'San Diego', 'CA', 'scripps ranch high school', ARRAY['scrippsranch.sandiegounified.org']),
  ('Westview High School', 'San Diego', 'CA', 'westview high school', ARRAY['powayusd.com', 'westview.powayusd.com']),
  ('Torrey Pines High School', 'San Diego', 'CA', 'torrey pines high school', ARRAY['powayusd.com', 'tp.powayusd.com']),
  ('San Marcos High School', 'San Marcos', 'CA', 'san marcos high school', ARRAY['smusd.org', 'smusd.us']),
  ('Carlsbad High School', 'Carlsbad', 'CA', 'carlsbad high school', ARRAY['carlsbadusd.net', 'carlsbad.k12.ca.us']),
  ('Vista High School', 'Vista', 'CA', 'vista high school', ARRAY['vistausd.org']),
  ('Rancho Buena Vista High School', 'Vista', 'CA', 'rancho buena vista high school', ARRAY['vistausd.org']),
  -- Texas
  ('Westlake High School', 'Austin', 'TX', 'westlake high school', ARRAY['eanesisd.net', 'westlake.eanesisd.net']),
  ('Lake Travis High School', 'Austin', 'TX', 'lake travis high school', ARRAY['ltisdschools.org']),
  ('Vandegrift High School', 'Austin', 'TX', 'vandegrift high school', ARRAY['leanderisd.org']),
  ('Cedar Park High School', 'Cedar Park', 'TX', 'cedar park high school', ARRAY['leanderisd.org']),
  ('Round Rock High School', 'Round Rock', 'TX', 'round rock high school', ARRAY['roundrockisd.org']),
  ('McNeil High School', 'Austin', 'TX', 'mcneil high school', ARRAY['roundrockisd.org']),
  ('Bowie High School', 'Austin', 'TX', 'bowie high school', ARRAY['austinisd.org']),
  ('Anderson High School', 'Austin', 'TX', 'anderson high school', ARRAY['austinisd.org']),
  ('Westwood High School', 'Austin', 'TX', 'westwood high school', ARRAY['roundrockisd.org']),
  ('Cedar Ridge High School', 'Round Rock', 'TX', 'cedar ridge high school', ARRAY['roundrockisd.org']),
  -- Florida
  ('Winter Park High School', 'Winter Park', 'FL', 'winter park high school', ARRAY['ocps.net', 'winterpark.ocps.net']),
  ('Dr. Phillips High School', 'Orlando', 'FL', 'dr phillips high school', ARRAY['ocps.net']),
  ('Olympia High School', 'Orlando', 'FL', 'olympia high school', ARRAY['ocps.net']),
  ('Boone High School', 'Orlando', 'FL', 'boone high school', ARRAY['ocps.net']),
  ('Edgewater High School', 'Orlando', 'FL', 'edgewater high school', ARRAY['ocps.net']),
  ('Lake Brantley High School', 'Altamonte Springs', 'FL', 'lake brantley high school', ARRAY['scps.k12.fl.us']),
  ('Lake Mary High School', 'Lake Mary', 'FL', 'lake mary high school', ARRAY['scps.k12.fl.us']),
  ('Seminole High School', 'Sanford', 'FL', 'seminole high school', ARRAY['scps.k12.fl.us']),
  ('Oviedo High School', 'Oviedo', 'FL', 'oviedo high school', ARRAY['scps.k12.fl.us']),
  ('Hagerty High School', 'Oviedo', 'FL', 'hagerty high school', ARRAY['scps.k12.fl.us']),
  -- New York
  ('Stuyvesant High School', 'New York', 'NY', 'stuyvesant high school', ARRAY['schools.nyc.gov', 'nyc.gov']),
  ('Bronx Science High School', 'Bronx', 'NY', 'bronx science high school', ARRAY['schools.nyc.gov']),
  ('Brooklyn Tech High School', 'Brooklyn', 'NY', 'brooklyn tech high school', ARRAY['schools.nyc.gov']),
  ('Townsend Harris High School', 'Queens', 'NY', 'townsend harris high school', ARRAY['schools.nyc.gov']),
  ('Eleanor Roosevelt High School', 'New York', 'NY', 'eleanor roosevelt high school', ARRAY['schools.nyc.gov']),
  ('Beacon High School', 'New York', 'NY', 'beacon high school', ARRAY['schools.nyc.gov']),
  ('Fiorello H. LaGuardia High School', 'New York', 'NY', 'fiorello h laguardia high school', ARRAY['schools.nyc.gov']),
  ('Scarsdale High School', 'Scarsdale', 'NY', 'scarsdale high school', ARRAY['scarsdaleschools.org']),
  ('Horace Greeley High School', 'Chappaqua', 'NY', 'horace greeley high school', ARRAY['chappaquaschools.org']),
  ('Byram Hills High School', 'Armonk', 'NY', 'byram hills high school', ARRAY['byramhills.org']),
  -- Illinois
  ('Walter Payton College Prep', 'Chicago', 'IL', 'walter payton college prep', ARRAY['cps.edu', 'chicagopublicschools.org']),
  ('Northside College Prep', 'Chicago', 'IL', 'northside college prep', ARRAY['cps.edu']),
  ('Jones College Prep', 'Chicago', 'IL', 'jones college prep', ARRAY['cps.edu']),
  ('Whitney Young High School', 'Chicago', 'IL', 'whitney young high school', ARRAY['cps.edu']),
  ('Lane Tech High School', 'Chicago', 'IL', 'lane tech high school', ARRAY['cps.edu']),
  ('New Trier High School', 'Winnetka', 'IL', 'new trier high school', ARRAY['newtrier.k12.il.us']),
  ('Hinsdale Central High School', 'Hinsdale', 'IL', 'hinsdale central high school', ARRAY['hinsdale86.org']),
  ('Glenbrook South High School', 'Glenview', 'IL', 'glenbrook south high school', ARRAY['glenbrook225.org']),
  ('Stevenson High School', 'Lincolnshire', 'IL', 'stevenson high school', ARRAY['d125.org']),
  ('Naperville North High School', 'Naperville', 'IL', 'naperville north high school', ARRAY['naperville203.org']),
  -- Washington
  ('Garfield High School', 'Seattle', 'WA', 'garfield high school', ARRAY['seattleschools.org']),
  ('Roosevelt High School', 'Seattle', 'WA', 'roosevelt high school', ARRAY['seattleschools.org']),
  ('Ballard High School', 'Seattle', 'WA', 'ballard high school', ARRAY['seattleschools.org']),
  ('Bellevue High School', 'Bellevue', 'WA', 'bellevue high school', ARRAY['bsd405.org']),
  ('Newport High School', 'Bellevue', 'WA', 'newport high school', ARRAY['bsd405.org']),
  ('Interlake High School', 'Bellevue', 'WA', 'interlake high school', ARRAY['bsd405.org']),
  ('Issaquah High School', 'Issaquah', 'WA', 'issaquah high school', ARRAY['issaquah.wednet.edu']),
  ('Skyline High School', 'Sammamish', 'WA', 'skyline high school', ARRAY['issaquah.wednet.edu']),
  ('Eastlake High School', 'Sammamish', 'WA', 'eastlake high school', ARRAY['lwsd.org']),
  ('Redmond High School', 'Redmond', 'WA', 'redmond high school', ARRAY['lwsd.org']),
  -- Colorado
  ('Cherry Creek High School', 'Greenwood Village', 'CO', 'cherry creek high school', ARRAY['cherrycreekschools.org']),
  ('Grandview High School', 'Aurora', 'CO', 'grandview high school', ARRAY['cherrycreekschools.org']),
  ('Smoky Hill High School', 'Aurora', 'CO', 'smoky hill high school', ARRAY['cherrycreekschools.org']),
  ('Fairview High School', 'Boulder', 'CO', 'fairview high school', ARRAY['bvsd.org']),
  ('Boulder High School', 'Boulder', 'CO', 'boulder high school', ARRAY['bvsd.org']),
  ('Monarch High School', 'Louisville', 'CO', 'monarch high school', ARRAY['bvsd.org']),
  ('Arapahoe High School', 'Centennial', 'CO', 'arapahoe high school', ARRAY['lps.k12.co.us']),
  ('Heritage High School', 'Littleton', 'CO', 'heritage high school', ARRAY['lps.k12.co.us']),
  ('Mountain Vista High School', 'Highlands Ranch', 'CO', 'mountain vista high school', ARRAY['dcsdk12.org']),
  ('Rock Canyon High School', 'Highlands Ranch', 'CO', 'rock canyon high school', ARRAY['dcsdk12.org']),
  -- Georgia
  ('North Gwinnett High School', 'Suwanee', 'GA', 'north gwinnett high school', ARRAY['gwinnett.k12.ga.us']),
  ('Lambert High School', 'Suwanee', 'GA', 'lambert high school', ARRAY['forsyth.k12.ga.us']),
  ('South Forsyth High School', 'Cumming', 'GA', 'south forsyth high school', ARRAY['forsyth.k12.ga.us']),
  ('West Forsyth High School', 'Cumming', 'GA', 'west forsyth high school', ARRAY['forsyth.k12.ga.us']),
  ('Milton High School', 'Milton', 'GA', 'milton high school', ARRAY['fultonschools.org']),
  ('Alpharetta High School', 'Alpharetta', 'GA', 'alpharetta high school', ARRAY['fultonschools.org']),
  ('Roswell High School', 'Roswell', 'GA', 'roswell high school', ARRAY['fultonschools.org']),
  ('Brookwood High School', 'Snellville', 'GA', 'brookwood high school', ARRAY['gwinnett.k12.ga.us']),
  ('Parkview High School', 'Lilburn', 'GA', 'parkview high school', ARRAY['gwinnett.k12.ga.us']),
  ('Mill Creek High School', 'Hoschton', 'GA', 'mill creek high school', ARRAY['gwinnett.k12.ga.us']),
  -- Massachusetts
  ('Boston Latin School', 'Boston', 'MA', 'boston latin school', ARRAY['bostonpublicschools.org']),
  ('Lexington High School', 'Lexington', 'MA', 'lexington high school', ARRAY['lexingtonma.org']),
  ('Newton South High School', 'Newton', 'MA', 'newton south high school', ARRAY['newton.k12.ma.us']),
  ('Newton North High School', 'Newton', 'MA', 'newton north high school', ARRAY['newton.k12.ma.us']),
  ('Brookline High School', 'Brookline', 'MA', 'brookline high school', ARRAY['brookline.k12.ma.us']),
  ('Wellesley High School', 'Wellesley', 'MA', 'wellesley high school', ARRAY['wellesleyps.org']),
  ('Acton-Boxborough Regional High School', 'Acton', 'MA', 'acton boxborough regional high school', ARRAY['abschools.org']),
  ('Westford Academy', 'Westford', 'MA', 'westford academy', ARRAY['westfordk12.us']),
  ('Needham High School', 'Needham', 'MA', 'needham high school', ARRAY['needham.k12.ma.us']),
  ('Lincoln-Sudbury Regional High School', 'Sudbury', 'MA', 'lincoln sudbury regional high school', ARRAY['lsrhs.net']),
  -- Arizona
  ('Basis Scottsdale', 'Scottsdale', 'AZ', 'basis scottsdale', ARRAY['basised.com', 'basis.scottsdale.org']),
  ('Desert Mountain High School', 'Scottsdale', 'AZ', 'desert mountain high school', ARRAY['susd.org']),
  ('Chaparral High School', 'Scottsdale', 'AZ', 'chaparral high school', ARRAY['susd.org']),
  ('Saguaro High School', 'Scottsdale', 'AZ', 'saguaro high school', ARRAY['susd.org']),
  ('Hamilton High School', 'Chandler', 'AZ', 'hamilton high school', ARRAY['cusd80.com']),
  ('Basha High School', 'Chandler', 'AZ', 'basha high school', ARRAY['cusd80.com']),
  ('Perry High School', 'Gilbert', 'AZ', 'perry high school', ARRAY['cusd80.com']),
  ('Mountain View High School', 'Mesa', 'AZ', 'mountain view high school', ARRAY['mpsaz.org']),
  ('Red Mountain High School', 'Mesa', 'AZ', 'red mountain high school', ARRAY['mpsaz.org']),
  ('Desert Vista High School', 'Phoenix', 'AZ', 'desert vista high school', ARRAY['tempeunion.org']),
  -- North Carolina
  ('Myers Park High School', 'Charlotte', 'NC', 'myers park high school', ARRAY['cms.k12.nc.us']),
  ('Ardrey Kell High School', 'Charlotte', 'NC', 'ardrey kell high school', ARRAY['cms.k12.nc.us']),
  ('Providence High School', 'Charlotte', 'NC', 'providence high school', ARRAY['cms.k12.nc.us']),
  ('Raleigh Charter High School', 'Raleigh', 'NC', 'raleigh charter high school', ARRAY['raleighcharterhs.org']),
  ('Enloe High School', 'Raleigh', 'NC', 'enloe high school', ARRAY['wcpss.net']),
  ('Green Hope High School', 'Cary', 'NC', 'green hope high school', ARRAY['wcpss.net']),
  ('Panther Creek High School', 'Cary', 'NC', 'panther creek high school', ARRAY['wcpss.net']),
  ('Apex Friendship High School', 'Apex', 'NC', 'apex friendship high school', ARRAY['wcpss.net']),
  ('Wakefield High School', 'Raleigh', 'NC', 'wakefield high school', ARRAY['wcpss.net']),
  ('Millbrook High School', 'Raleigh', 'NC', 'millbrook high school', ARRAY['wcpss.net']),
  -- Michigan
  ('Troy High School', 'Troy', 'MI', 'troy high school', ARRAY['troy.k12.mi.us']),
  ('Athens High School', 'Troy', 'MI', 'athens high school', ARRAY['troy.k12.mi.us']),
  ('Bloomfield Hills High School', 'Bloomfield Hills', 'MI', 'bloomfield hills high school', ARRAY['bloomfield.org']),
  ('Brother Rice High School', 'Bloomfield Hills', 'MI', 'brother rice high school', ARRAY['brrice.edu']),
  ('Northville High School', 'Northville', 'MI', 'northville high school', ARRAY['northvilleschools.org']),
  ('Novi High School', 'Novi', 'MI', 'novi high school', ARRAY['novi.k12.mi.us']),
  ('Plymouth High School', 'Canton', 'MI', 'plymouth high school', ARRAY['pccsk12.com']),
  ('Salem High School', 'Canton', 'MI', 'salem high school', ARRAY['pccsk12.com']),
  ('Canton High School', 'Canton', 'MI', 'canton high school', ARRAY['pccsk12.com']),
  ('Ann Arbor Pioneer High School', 'Ann Arbor', 'MI', 'ann arbor pioneer high school', ARRAY['aaps.k12.mi.us']),
  -- Ohio
  ('Upper Arlington High School', 'Upper Arlington', 'OH', 'upper arlington high school', ARRAY['uaschools.org']),
  ('Dublin Jerome High School', 'Dublin', 'OH', 'dublin jerome high school', ARRAY['dublinschools.net']),
  ('Dublin Coffman High School', 'Dublin', 'OH', 'dublin coffman high school', ARRAY['dublinschools.net']),
  ('Dublin Scioto High School', 'Dublin', 'OH', 'dublin scioto high school', ARRAY['dublinschools.net']),
  ('Olentangy Liberty High School', 'Powell', 'OH', 'olentangy liberty high school', ARRAY['olentangy.k12.oh.us']),
  ('Olentangy Orange High School', 'Lewis Center', 'OH', 'olentangy orange high school', ARRAY['olentangy.k12.oh.us']),
  ('New Albany High School', 'New Albany', 'OH', 'new albany high school', ARRAY['napls.us']),
  ('Mason High School', 'Mason', 'OH', 'mason high school', ARRAY['masonohioschools.com']),
  ('Sycamore High School', 'Cincinnati', 'OH', 'sycamore high school', ARRAY['sycamoreschools.org']),
  ('Walnut Hills High School', 'Cincinnati', 'OH', 'walnut hills high school', ARRAY['cps-k12.org']),
  -- Virginia
  ('Thomas Jefferson High School for Science and Technology', 'Alexandria', 'VA', 'thomas jefferson high school for science and technology', ARRAY['fcps.edu']),
  ('Langley High School', 'McLean', 'VA', 'langley high school', ARRAY['fcps.edu']),
  ('McLean High School', 'McLean', 'VA', 'mclean high school', ARRAY['fcps.edu']),
  ('Madison High School', 'Vienna', 'VA', 'madison high school', ARRAY['fcps.edu']),
  ('Oakton High School', 'Vienna', 'VA', 'oakton high school', ARRAY['fcps.edu']),
  ('Chantilly High School', 'Chantilly', 'VA', 'chantilly high school', ARRAY['fcps.edu']),
  ('Centreville High School', 'Clifton', 'VA', 'centreville high school', ARRAY['fcps.edu']),
  ('Robinson Secondary School', 'Fairfax', 'VA', 'robinson secondary school', ARRAY['fcps.edu']),
  ('Lake Braddock Secondary School', 'Burke', 'VA', 'lake braddock secondary school', ARRAY['fcps.edu']),
  ('Westfield High School', 'Chantilly', 'VA', 'westfield high school', ARRAY['fcps.edu']),
  -- Oregon
  ('Lincoln High School', 'Portland', 'OR', 'lincoln high school portland', ARRAY['pps.net', 'portland.k12.or.us']),
  ('Grant High School', 'Portland', 'OR', 'grant high school', ARRAY['pps.net']),
  ('Jesuit High School', 'Portland', 'OR', 'jesuit high school', ARRAY['jesuitportland.org']),
  ('Sunset High School', 'Portland', 'OR', 'sunset high school', ARRAY['beaverton.k12.or.us']),
  ('Westview High School', 'Portland', 'OR', 'westview high school portland', ARRAY['beaverton.k12.or.us']),
  ('Southridge High School', 'Beaverton', 'OR', 'southridge high school', ARRAY['beaverton.k12.or.us']),
  ('Lake Oswego High School', 'Lake Oswego', 'OR', 'lake oswego high school', ARRAY['loswego.k12.or.us']),
  ('Lakeridge High School', 'Lake Oswego', 'OR', 'lakeridge high school', ARRAY['loswego.k12.or.us']),
  ('West Linn High School', 'West Linn', 'OR', 'west linn high school', ARRAY['wlwv.k12.or.us']),
  ('Tigard High School', 'Tigard', 'OR', 'tigard high school', ARRAY['ttsd.k12.or.us']);
